- name: Install Labgrid Coordinator service file
  become: true
  copy:
    dest: /etc/systemd/system/labgrid-coordinator.service
    src: ../files/labgrid-coordinator.service
    mode: '0644'
  register: coordinator_service

- name: Start Labgrid Coordinator
  become: true
  systemd:
    name: labgrid-coordinator
    daemon_reload: yes
    state: "{{ 'restarted' if coordinator_service.changed else 'started' }}"
    enabled: true

- name: Configure Labgrid places
  delegate_to: localhost
  ansible.builtin.command:
    argv:
      - "{{ role_path }}/../../../run-venv"
      - "{{ role_path }}/../../../labgrid/contrib/sync-places.py"
      - "--proxy={{ inventory_hostname }}"
      - "sync"
      - "{{ role_path }}/../../host_files/{{ inventory_hostname }}/places.yaml"
  register: result
  changed_when: result.stdout | length > 0
