apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  battlestar/app: tekton

resources:
  - "http://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml"
  - "http://storage.googleapis.com/tekton-releases/dashboard/latest/tekton-dashboard-release.yaml"
  - "http://storage.googleapis.com/tekton-releases/triggers/latest/release.yaml"
  - "ingress.yaml"
