- name: "Partition {{ localdisk }}"
  become: true
  community.general.parted:
    device: '{{ localdisk }}'
    number: 1
    state: present
    part_start: 0%
    part_end: 100%
    fs_type: ext4
    label: gpt

- name: "Format partition {{ localdisk }}1"
  become: true
  community.general.filesystem:
    dev: '{{ localdisk }}1'
    fstype: ext4
    resizefs: yes

- name: "Mount partition {{ localdisk }}1"
  become: true
  ansible.posix.mount:
    src: '{{ localdisk }}1'
    path: '/mnt/local-disks/{{ localdisk }}'
    state: mounted
    fstype: ext4
    boot: yes

- name: "Create mount location {{ item }}"
  become: true
  file:
    path: '/mnt/local-disks/{{ localdisk }}/{{ item }}'
    state: directory
    mode: 0755
  loop: "{{ range( localcount ) | list }}"

- name: "Bind mount disk {{ item }}"
  become: true
  ansible.posix.mount:
    src: '/mnt/local-disks/{{ localdisk }}/{{ item }}'
    path: '/mnt/fast-disks/{{ item }}'
    state: mounted
    fstype: none
    opts: bind
    boot: yes
  loop: "{{ range( localcount ) | list }}"

