#! /bin/sh

set -e

TOP_DIR="$(dirname $0)"

REV="$(git -C $TOP_DIR/labgrid rev-parse HEAD) $(git -C $TOP_DIR rev-parse HEAD)"

if [ ! -e "$TOP_DIR/venv/rev.txt" ] || [ "$(cat "$TOP_DIR/venv/rev.txt")" != "$REV" ]; then
    (
    python3 -m venv $TOP_DIR/venv
    . $TOP_DIR/venv/bin/activate
    python3 -m pip install -U pip
    python3 -m pip install -r $TOP_DIR/labgrid/requirements.txt
    cd $TOP_DIR/labgrid
    ./setup.py install
    )

    echo "$REV" > $TOP_DIR/venv/rev.txt
fi

set +e
if [ -n "$1" ]; then
    . $TOP_DIR/venv/bin/activate
    exec "$@"
fi
