apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: labgrid-coordinator
  labels:
    app: labgrid-coordinator
spec:
  selector:
    matchLabels:
      app: labgrid-coordinator
  template:
    metadata:
      labels:
        app: labgrid-coordinator
    spec:
      nodeSelector:
        labgrid-coordinator: "yes"

      tolerations:
        - key: edgetype
          operator: Equal
          value: labgrid
          effect: NoExecute

      hostNetwork: true

      containers:
        - name: labgrid-coordinator
          image: joshuawatt/labgrid-coordinator:2020.12.14.1
          volumeMounts:
            - name: crossbar
              mountPath: /opt/crossbar
          ports:
            - containerPort: 20408

      volumes:
        - name: crossbar
          hostPath:
            path: /opt/crossbar
            type: DirectoryOrCreate

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: labgrid-exporter
  labels:
    app: labgrid-exporter
spec:
  selector:
    matchLabels:
      app: labgrid-exporter
  template:
    metadata:
      labels:
        app: labgrid-exporter
    spec:
      nodeSelector:
        labgrid-exporter: "yes"

      tolerations:
        - key: edgetype
          operator: Equal
          value: labgrid
          effect: NoExecute

      hostNetwork: true

      containers:
        - name: labgrid-exporter
          image: joshuawatt/labgrid-exporter:2020.12.14.1
          command: ["/entrypoint.sh"]
          # TODO: It would be really nice to have a way to look up the
          # coordinator via a name instead of an IP address
          args: ["-x", "ws://192.168.1.200:20408/ws", "-i"]
          volumeMounts:
            - name: exporter-conf
              mountPath: /opt/conf/exporter.yaml
              readOnly: true
            - name: host-usb
              mountPath: /dev/bus/usb
              readOnly: true
            - name: host-udev
              mountPath: /run/udev
              readOnly: true
            - name: labgrid-cache
              mountPath: /var/cache/labgrid
          securityContext:
            # TODO: Fix this!
            privileged: true

      volumes:
        - name: exporter-conf
          hostPath:
            path: /etc/labgrid/configuration.yaml
            type: File

        - name: host-usb
          hostPath:
            path: /dev/bus/usb
            type: Directory

        - name: host-udev
          hostPath:
            path: /run/udev
            type: Directory

        - name: labgrid-cache
          hostPath:
            path: /var/cache/labgrid
            type: Directory
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pdudaemon
  labels:
    app: pdudaemon
spec:
  selector:
    matchLabels:
      app: pdudaemon
  template:
    metadata:
      labels:
        app: pdudaemon
    spec:
      nodeSelector:
        pdudaemon: "yes"

      tolerations:
        - key: edgetype
          operator: Equal
          value: labgrid
          effect: NoExecute

      hostNetwork: true

      containers:
        - name: pdudaemon
          image: joshuawatt/pdudaemon:2020.12.14.1
          volumeMounts:
            - name: pdudaemon-conf
              mountPath: /config/pdudaemon.conf
              readOnly: true
            - name: host-usb
              mountPath: /dev/bus/usb
              readOnly: true
            - name: host-udev
              mountPath: /run/udev
              readOnly: true
          ports:
            - containerPort: 16421
          securityContext:
            # TODO: Fix this!
            privileged: true

      volumes:
        - name: pdudaemon-conf
          hostPath:
            path: /etc/pdudaemon/pdudaemon.conf
            type: File

        - name: host-usb
          hostPath:
            path: /dev/bus/usb
            type: Directory

        - name: host-udev
          hostPath:
            path: /run/udev
            type: Directory
---
# This service gives the Tekton pipelines a DNS name they can use to ssh into
# the labgrid-coordinator. It's not ideal because there could theoretically be
# several labgrid coordinators to choose from, but the service only works for
# one. There probably some better way to do this, but I don't know what it is
apiVersion: v1
kind: Service
metadata:
  name: labgrid-proxy
spec:
  selector:
    app: labgrid-coordinator
  ports:
    - protocol: TCP
      port: 22
