{%- for product in ["qemux86-64", "raspberrypi4", "raspberrypi3", "rockpi4", "tinkerboard", "rockpix"] %}
{%- for version in ["default", "hardknott"] %}
{%- for upstream in [false, true] %}
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: {{ product }}-{{ version }}{{ "-upstream" if upstream else "" }}-
  namespace: yocto-build
  labels:
    product: {{ product }}
    version: {{ version }}
    upstream: "{{ 'true' if upstream else 'false' }}"
spec:
  serviceAccountName: yocto-doom-demo-user
  pipelineRef:
    name: yocto-whisk-pipeline
  params:
    - name: url
      value: https://github.com/JPEWdev/yocto-doom-demo.git
    - name: revision
      value: main
    - name: depth
      value: "1"
    - name: products
      value: "{{ product }}"
    - name: mode
      value: development
    - name: site
      value: tekton
    - name: version
      value: "{{ version }}"
    - name: submoduleRemote
      value: "{{ 'true' if upstream else 'false' }}"
    - name: labgridProxy
      value: coordinator-labgrid.http-tunnel
    - name: labgridProxyUser
      value: labgrid
    - name: labgridDomain
      value: "*-labgrid"
    - name: labgridProxyCommand
      value: "ssh $PROXY -W %h.local:%p"
    - name: labgridTestDirectory
      value: "ci/{{ product }}"
    - name: labgridEnvFile
      value: "ci/{{ product }}/env.yaml"
    - name: hashServer
      value: "yocto-hashserv:8686"
  workspaces:
    - name: build-workspace
      subPath: build
      volumeClaimTemplate:
        spec:
          storageClassName: fast-disks
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 32Gi
  timeout: 10h
  podTemplate:
    priorityClassName: yocto-build-priority
  taskRunSpecs:
    - pipelineTaskName: clone
      taskPodTemplate:
        priorityClassName: yocto-clone-priority
{%- endfor %}
{%- endfor %}
{%- endfor %}
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: check-
  namespace: yocto-build
spec:
  serviceAccountName: yocto-doom-demo-user
  pipelineRef:
    name: black-check-pipeline
  params:
    - name: url
      value: https://github.com/JPEWdev/yocto-doom-demo.git
    - name: revision
      value: main
  workspaces:
    - name: build-workspace
      subPath: build
      volumeClaimTemplate:
        spec:
          storageClassName: fast-disks
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 64Gi
  timeout: 10h
