apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: http-tunnel

commonLabels:
  battlestar/app: http-tunnel

resources:
  - namespace.yaml
  - deployment.yaml
  - node-port.yaml
  - coordinator-labgrid.yaml

