apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  battlestar/app: ingress

resources:
  - "https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.48.1/deploy/static/provider/baremetal/deploy.yaml"

patchesJSON6902:
  - target:
      version: v1
      kind: Service
      name: ingress-nginx-controller
      namespace: ingress-nginx
    patch: |-
      - op: add
        path: /spec/ports/0/nodePort
        value: 30080
      - op: add
        path: /spec/ports/1/nodePort
        value: 30443

