apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubevirt

commonLabels:
  battlestar/app: kubevirt-operator

resources:
  - 'https://github.com/kubevirt/kubevirt/releases/download/v0.43.0/kubevirt-cr.yaml'

# Note: You have to manually install kubevirt once, but after that it will be
# tied to the version of the operator
# kubectl create -f https://github.com/kubevirt/kubevirt/releases/download/v0.43.0/kubevirt-operator.yaml
