- name: 'Create user adama user'
  become: true
  user:
    name: 'adama'
    append: yes
    state: present
    createhome: yes
    shell: /bin/bash

- name: 'Allow adama to have passwordless sudo'
  become: true
  lineinfile:
    dest: /etc/sudoers
    line: 'adama ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: 'Set up authorized keys for adama'
  become: true
  authorized_key:
    user: 'adama'
    key: '{{ item }}'
    exclusive: yes
  with_file:
    - ../../../../keys/id_rsa.pub

- name: Install avahi daemon
  become: true
  ansible.builtin.apt:
    name: avahi-daemon
    state: present
    update_cache: true


