apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nfs-provisioning

commonLabels:
  app: nfs-provisioning

resources:
  - namespace.yaml
  - rbac.yaml
  - class.yaml
  - deployment.yaml

