apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

commonLabels:
  app: pipelines

resources:
  - pipelines-namespace.yaml
  - "https://raw.githubusercontent.com/tektoncd/catalog/master/task/black/0.1/black.yaml"
  - "https://raw.githubusercontent.com/tektoncd/catalog/master/task/git-clone/0.2/git-clone.yaml"
  - "https://raw.githubusercontent.com/tektoncd/catalog/master/task/kubernetes-actions/0.1/kubernetes-actions.yaml"
  - "https://raw.githubusercontent.com/tektoncd/catalog/master/task/tkn/0.2/tkn.yaml"
  - yocto-cache.yaml
  - crops-clone.yaml
  - yocto-whisk-build.yaml
  - yocto-whisk-pipeline.yaml
  - yocto-doom-demo-pipeline.yaml
