apiVersion: v1
kind: Namespace
metadata:
  name: yocto-build
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: yocto-clone-priority
# Set this to a low value. If the node becomes resource constrained, kill these
# pods first
value: -1000
preemptionPolicy: Never
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: yocto-build-priority
# Set this to a low value. If the node becomes resource constrained, kill these
# pods first
value: -999
preemptionPolicy: Never

# Note: We can define more priority classes for builds with higher priorities,
# as long as the preemptionPolicy is Never. This effectively allows builds to
# be run sooner, but prevents them from stopping any builds currently in
# progress
---
#apiVersion: v1
#kind: LimitRange
#metadata:
#  name: yocto-build-limit
#  namespace: yocto-build
#spec:
#  limits:
#    - type: Container
#      defaultRequest:
#        memory: 8Gi
#        cpu: 6.5
#      default:
#        memory: 8Gi
#        cpu: 6.5
#
