apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: yocto-whisk-pipeline
  namespace: yocto-build
spec:
  params:
    - name: url
      description: git url to clone
      type: string
    - name: revision
      description: git revision to checkout (branch, tag, sha, ref…)
      type: string
      default: ""
    - name: refspec
      description: (optional) git refspec to fetch before checking out revision
      type: string
      default: ""
    - name: depth
      description: shallow clone depth
      type: string
      default: ""
    - name: subdirectory
      description: clone and build in this subdirectory under the build workspace
      type: string
      default: ""
    - name: products
      description: The product(s) to build
      type: string
    - name: mode
      description: The mode to build
      type: string
    - name: site
      description: The site where build
      type: string
    - name: version
      description: The version to build against
      type: string
      default: default
    - name: initScript
      description: The whisk init script
      type: string
      default: "./init-build-env"
    - name: buildDir
      description: The build directory
      type: string
      default: "build"
    - name: buildTargets
      description: The bitbake build target
      type: string
      default: "all-targets"
    - name: submoduleRemote
      description: Use submodule remote tracking branches instead of recorded SHA-1
      type: string
      default: "false"

  workspaces:
    - name: build-workspace
      description: The build workspace
  tasks:
    - name: clone
      taskRef:
        name: crops-clone
      workspaces:
        - name: output
          workspace: build-workspace
      params:
        - name: url
          value: "$(params.url)"
        - name: revision
          value: "$(params.revision)"
        - name: refspec
          value: "$(params.refspec)"
        - name: submodules
          value: "true"
        - name: depth
          value: "$(params.depth)"
        - name: subdirectory
          value: "$(params.subdirectory)"
        - name: image
          value: "joshuawatt/crops:ubuntu-20.04-base"
        - name: submoduleRemote
          value: "$(params.submoduleRemote)"
    - name: validate
      taskRef:
        name: yocto-whisk-validate
      runAfter:
        - clone
      workspaces:
        - name: build
          workspace: build-workspace
      params:
        - name: subdirectory
          value: "$(params.subdirectory)"
    - name: build
      taskRef:
        name: yocto-whisk-build
      runAfter:
        - validate
      workspaces:
        - name: build
          workspace: build-workspace
      params:
        - name: products
          value: "$(params.products)"
        - name: mode
          value: "$(params.mode)"
        - name: site
          value: "$(params.site)"
        - name: version
          value: "$(params.version)"
        - name: initScript
          value: "$(params.initScript)"
        - name: buildDir
          value: "$(params.buildDir)"
        - name: buildTargets
          value: "$(params.buildTargets)"
        - name: fetch
          value: "false"
        - name: subdirectory
          value: "$(params.subdirectory)"

