apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: yocto-whisk-test
  namespace: yocto-build
spec:
  workspaces:
    - name: build
      description: The build workspace
  params:
    - name: initScript
      description: The whisk init script
      type: string
      default: "./init-build-env"
    - name: subdirectory
      description: build in this subdirectory under the build workspace
      type: string
      default: ""
    - name: testDirectory
      description: Pytest test directory
      type: string
      default: "."
    - name: envFile
      description: Location of the LabGrid pytest environment file
      type: string
  stepTemplate:
    resources:
      requests:
        cpu: "1"
        memory: "6Gi"
        # This isn't ideal because it limits what nodes we can run on, even if
        # we don't need qemu
        devices.kubevirt.io/kvm: "1"
      limits:
        devices.kubevirt.io/kvm: "1"
  steps:
    - name: get-environment
      image: joshuawatt/crops-ubuntu-20.04:2021.5.3.1
      script: |
        cd $(workspaces.build.path)/$(params.subdirectory)
        . $(params.initScript)
        bitbake -e > $(workspaces.build.path)/env.txt

    - name: test
      image: joshuawatt/labgrid-client:2021.2.25.2
      script: |
        SSH_HOME=/root
        . $(workspaces.build.path)/labgrid.env

        eval `grep '^WHISK_DEPLOY_DIR_BASE=' $(workspaces.build.path)/env.txt`

        export LG_DEPLOY_DIR="$WHISK_DEPLOY_DIR_BASE"

        cd $(workspaces.build.path)/$(params.subdirectory)
        pytest -v --lg-env=$(params.envFile) $(params.testDirectory)

