apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: yocto-whisk-pipeline
  namespace: yocto-build
spec:
  params:
    - name: url
      description: git url to clone
      type: string
    - name: revision
      description: git revision to checkout (branch, tag, sha, ref…)
      type: string
      default: ""
    - name: refspec
      description: (optional) git refspec to fetch before checking out revision
      type: string
      default: ""
    - name: depth
      description: shallow clone depth
      type: string
      default: ""
    - name: subdirectory
      description: clone and build in this subdirectory under the build workspace
      type: string
      default: ""
    - name: products
      description: The product(s) to build
      type: string
    - name: mode
      description: The mode to build
      type: string
    - name: site
      description: The site where build
      type: string
    - name: version
      description: The version to build against
      type: string
      default: default
    - name: initScript
      description: The whisk init script
      type: string
      default: "./init-build-env"
    - name: buildDir
      description: The build directory
      type: string
      default: "build"
    - name: buildTargets
      description: The bitbake build target
      type: string
      default: "all-targets"
    - name: submoduleRemote
      description: Use submodule remote tracking branches instead of recorded SHA-1
      type: string
      default: "false"
    - name: hashServer
      description: Hash equivalence server address
      type: string
      default: ""
    - name: labgridProxy
      description: Labgrid SSH Proxy
      type: string
      default: ""
    - name: labgridProxyUser
      description: Labgrid SSH Proxy user
      type: string
      default: ""
    - name: labgridDomain
      description: Domain glob for labgrid exporters
      type: string
      default: ""
    - name: labgridProxyCommand
      description: The command to use to access labgrid export servers behind the proxy
      type: string
      default: "ssh $PROXY -W %h:%p"
    - name: labgridTestDirectory
      description: Location of the pytest files
      type: string
    - name: labgridEnvFile
      description: Location of the LabGrid pytest environment file
      type: string

  workspaces:
    - name: build-workspace
      description: The build workspace
  tasks:
    - name: clone
      taskRef:
        name: crops-clone
      workspaces:
        - name: output
          workspace: build-workspace
      params:
        - name: url
          value: "$(params.url)"
        - name: revision
          value: "$(params.revision)"
        - name: refspec
          value: "$(params.refspec)"
        - name: submodules
          value: "true"
        - name: depth
          value: "$(params.depth)"
        - name: subdirectory
          value: "$(params.subdirectory)"
        - name: image
          value: "joshuawatt/crops:ubuntu-20.04-base"
        - name: submoduleRemote
          value: "$(params.submoduleRemote)"

    - name: validate
      taskRef:
        name: yocto-whisk-validate
      runAfter:
        - clone
      workspaces:
        - name: build
          workspace: build-workspace
      params:
        - name: subdirectory
          value: "$(params.subdirectory)"

    - name: build
      taskRef:
        name: yocto-whisk-build
      runAfter:
        - validate
      workspaces:
        - name: build
          workspace: build-workspace
      params:
        - name: products
          value: "$(params.products)"
        - name: mode
          value: "$(params.mode)"
        - name: site
          value: "$(params.site)"
        - name: version
          value: "$(params.version)"
        - name: initScript
          value: "$(params.initScript)"
        - name: buildDir
          value: "$(params.buildDir)"
        - name: buildTargets
          value: "$(params.buildTargets)"
        - name: fetch
          value: "false"
        - name: subdirectory
          value: "$(params.subdirectory)"
        - name: hashServer
          value: "$(params.hashServer)"

    - name: labgrid-reserve
      taskRef:
        name: labgrid-reserve
      runAfter:
        - build
      params:
        - name: envFile
          value: "$(params.subdirectory)/$(params.labgridEnvFile)"
        - name: tag
          value: "product=$(params.products)"
        - name: proxy
          value: "$(params.labgridProxy)"
        - name: proxyUser
          value: "$(params.labgridProxyUser)"
        - name: domain
          value: "$(params.labgridDomain)"
        - name: proxyCommand
          value: "$(params.labgridProxyCommand)"
      workspaces:
        - name: labgrid
          workspace: build-workspace

    - name: test
      taskRef:
        name: yocto-whisk-test
      runAfter:
        - labgrid-reserve
      params:
        - name: subdirectory
          value: "$(params.subdirectory)"
        - name: initScript
          value: "$(params.initScript)"
        - name: testDirectory
          value: "$(params.labgridTestDirectory)"
        - name: envFile
          value: "$(params.labgridEnvFile)"
      workspaces:
        - name: build
          workspace: build-workspace

  finally:
    - name: labgrid-release
      taskRef:
        name: labgrid-release
      workspaces:
        - name: labgrid
          workspace: build-workspace

