- hosts: galactica.local
  become: yes
  gather_facts: false
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

    - name: install jq
      apt:
        pkg:
          - jq
        state: present
        update_cache: true

- hosts: workers
  become: yes
  tasks:
    - name: join cluster
      shell: |
        set -eu
        {{ hostvars['galactica.local'].join_command }}
        touch node_joined.txt
      args:
        chdir: $HOME
        creates: node_joined.txt

    - name: Bootstrap TLS
      lineinfile:
        path: /var/lib/kubelet/config.yaml
        regexp: "^serverTLSBootstrap:"
        line: "serverTLSBootstrap: true"
      register: kubelet_config

    - block:
        - name: restart kubelet
          systemd:
            name: kubelet
            state: restarted

        - name: approve certificate
          shell: |
            set -eu
            sleep 30
            CERT="$(kubectl get csr -o json | jq -r '[.items[] | select(.spec.username=="system:node:{{ hostvars[inventory_hostname]['ansible_facts']['hostname'] }}")][0].metadata.name')"
            echo "CERT=$CERT"
            test -n "$CERT"
            kubectl certificate approve $CERT
          delegate_to: galactica.local

      when: kubelet_config.changed

