- hosts:
    - galactica.local
    - starbuck.local
    - viper.local
  vars:
    disk: /dev/sdb
    num_mounts: 10

  become: yes
  tasks:
    - name: "Partition {{ disk }}"
      community.general.parted:
        device: '{{ disk }}'
        number: 1
        state: present
        part_start: 0%
        part_end: 100%
        fs_type: ext4
        label: gpt

    - name: "Format partition {{ disk }}1"
      community.general.filesystem:
        dev: '{{ disk }}1'
        fstype: ext4
        resizefs: yes

    - name: "Mount partition {{ disk }}1"
      ansible.posix.mount:
        src: '{{ disk }}1'
        path: '/mnt/local-disks/{{ disk }}'
        state: mounted
        fstype: ext4
        boot: yes

    - name: "Create mount location {{ item }}"
      file:
        path: '/mnt/local-disks/{{ disk }}/{{ item }}'
        state: directory
        mode: 0755
      loop: "{{ range( num_mounts ) | list }}"

    - name: "Bind mount disk {{ item }}"
      ansible.posix.mount:
        src: '/mnt/local-disks/{{ disk }}/{{ item }}'
        path: '/mnt/fast-disks/{{ item }}'
        state: mounted
        fstype: none
        opts: bind
        boot: yes
      loop: "{{ range( num_mounts ) | list }}"
