- hosts: galactica.local
  become: yes
  gather_facts: true
#  tasks:
#    - name: get token
#      shell: keadm gettoken
#      register: gettoken_command_raw
#
#    - name: set token
#      set_fact:
#        join_token: "{{ gettoken_command_raw.stdout_lines[0] }}"
#        master_ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
#
#- hosts: edge
#  become: yes
#  tasks:
#    - name: install keadm
#      unarchive:
#        src: https://github.com/kubeedge/kubeedge/releases/download/v1.4.0/keadm-v1.4.0-linux-arm.tar.gz
#        remote_src: true
#        dest: /usr/local/bin
#        extra_opts:
#          - --strip-components=2
#      args:
#        creates: /usr/local/bin/keadm
#      when: ansible_facts['machine'] == 'armv7l'
#
#    - name: install keadm
#      unarchive:
#        src: https://github.com/kubeedge/kubeedge/releases/download/v1.4.0/keadm-v1.4.0-linux-amd64.tar.gz
#        remote_src: true
#        dest: /usr/local/bin
#        extra_opts:
#          - --strip-components=2
#      args:
#        creates: /usr/local/bin/keadm
#      when: ansible_facts['machine'] == 'x86_64'
#
#    - name: join cluster
#      shell: |
#        set -eu
#        keadm join --cloudcore-ipport={{ hostvars['galactica.local'].master_ip }}:10000 --token={{ hostvars['galactica.local'].join_token }}
#        touch node_joined.txt
#        sleep 240
#      args:
#        chdir: $HOME
#        creates: node_joined.txt
#
