- hosts: master
  become: yes
  gather_facts: false
  tasks:
    - name: get token
      shell: keadm gettoken
      register: gettoken_command_raw

    - name: set token
      set_fact:
        join_token: "{{ gettoken_command_raw.stdout_lines[0] }}"
        master_ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"

- hosts: edge-nodes
  become: yes
  tasks:
    - name: join cluster
      shell: |
        keadm join --cloudcore-ipport={{ hostvars['master'].master_ip }}:10000 --token={{ hostvars['master'].join_token }} && touch node_joined.txt
      args:
        chdir: $HOME
        creates: node_joined.txt

