- hosts: all
  become: yes
  tasks:
    - name: install Docker
      apt:
        name: docker.io
        state: present
        update_cache: true

    - name: configure docker to use systemd
      copy:
        content: |
          {
            "exec-opts": ["native.cgroupdriver=systemd"],
            "log-driver": "json-file",
            "log-opts": {
              "max-size": "100m"
            },
            "storage-driver": "overlay2"
          }
        dest: /etc/docker/daemon.json

    - name: make docker systemd directory
      file:
        path: /etc/systemd/system/docker.service.d
        state: directory

    - name: restart docker
      systemd:
        name: docker
        daemon_reload: yes
        state: reloaded
        enabled: true

    - name: install APT Transport HTTPS
      apt:
        name: apt-transport-https
        state: present

    - name: add Kubernetes apt-key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: add Kubernetes' APT repository
      apt_repository:
       repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
       state: present
       filename: 'kubernetes'

    - name: install kubelet
      apt:
        name: kubelet=1.19.0-00
        state: present
        update_cache: true

    - name: install kubeadm
      apt:
        name: kubeadm=1.19.0-00
        state: present

    - name: bridge iptable
      ansible.posix.sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: '1'
        sysctl_file: /etc/sysctl.d/k8s.conf

    - name: bridge ip6table
      ansible.posix.sysctl:
        name: net.bridge.bridge-nf-call-ip6tables
        value: '1'
        sysctl_file: /etc/sysctl.d/k8s.conf

    - name: Disable SWAP since kubernetes can't work with swap enabled (1/2)
      shell: |
        swapoff -a

    - name: Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
      replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        replace: '# \1'

    - name: mark packages
      shell: apt-mark hold kubelet kubeadm kubectl

- hosts: master
  become: yes
  tasks:
    - name: install kubectl
      apt:
        name: kubectl=1.19.0-00
        state: present
        force: yes

    - name: mark packages
      shell: apt-mark hold kubectl

