apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  battlestar/app: certs

resources:
  - "https://github.com/jetstack/cert-manager/releases/download/v1.4.1/cert-manager.yaml"
  - letsencrypt.yaml
